---
- name: Disable and Comment Swap 01
  hosts: servers
  become: yes
  tasks:

   - name: Disable Swap
     sysctl:
       name: vm.swappiness
       value: 0

   - name: Turn off Swap
     command: swapoff -a

   - name: Comment Swap Entry in fstab
     lineinfile:
       path: /etc/fstab
       regexp: '^/dev/mapper/.*swap.*'
       line: '#\g<0>'

   - name: Disable SELinux and set to disabled  02
     become: true
     lineinfile:
      path: /etc/selinux/config
      regexp: '^SELINUX='
      line: 'SELINUX=disabled'
      state: present
   
   - name: Turn off selinux now
     command: setenforce 0
     
   - name: Stop firewall  03
     command: systemctl stop firewalld

   - name: Write to containerd.conf file  - Setup configurations for containerd 01
     copy:
       dest: /etc/modules-load.d/containerd.conf
       content: |
          overlay
          br_netfilter
        
   - name: Write to 99-kubernetes-cri.conf file
     copy:
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.ipv4.ip_forward                 = 1
          net.bridge.bridge-nf-call-ip6tables = 1
        dest: /etc/sysctl.d/99-kubernetes-cri.conf
        
   - name: apply changes to containerd 
     command: sysctl --system
     
   - name: Install Containerd  - run time installer 01
     yum:
              name: 
               - yum-utils
               - device-mapper-persistent-data
               - lvm2
              state: present
              
   - name: Add docker repository because no direct redhat repo 02 
     yum_repository:
        name: docker-ce
        description: Docker CE YUM repository
        baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg
        enabled: yes
        
   - name: Install Containerd  - run time installer 03
     yum:
              name: containerd
              state: present
   
   - name: Configure containerd 04
     command: mkdir -p /etc/containerd
     
   - name: Configuration copy to config file 04
     command: containerd config default > /etc/containerd/config.toml    

   - name: Restart containerd  05
     service:
           name: containerd
           enabled: true
           state: restarted
      
   - name: Install Kubernetes- Add yum repo file for Kubernetes - 01
     copy:
       content: |
         [kubernetes]
         name=Kubernetes
         baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
         enabled=1
         gpgcheck=1
         repo_gpgcheck=1
         gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
       dest: /etc/yum.repos.d/kubernetes.repo 
    
   - name: Install kubernetes
     yum:
       name: 
         - kubelet
         - kubeadm
         - kubectl
       state: present
       disable_excludes: kubernetes
     
   - name: enable service on sertup 02
     command: systemctl enable --now kubelet
     
   - name: edit config swap off 03
     command: echo 'KUBELET_EXTRA_ARGS="--fail-swap-on=false"' > /etc/sysconfig/kubelet
     
   - name: start kubelet service 04 
     command: systemctl start kubelet 
